### PR TITLE
Distribution.Nixpkgs.Haskell.FromCabal: mainProgram check buildable

### PR DESCRIPTION
**Pull request by sternenseemann**
Naturally only a buildable executable can be the mainProgram. Checking
this property eliminates some false positive mainPrograms and also gets
rid of some cases where it wasn't recognized properly. pandoc still
eludes cabal2nix, probably something strange going on with flag
resolution.

### CODE REVIEW

**Comment by maralorn** [comment]
This looks like it introduces a lot of false negatives? e.g. brittany certainly has a sensible mainProgram?

**Comment by sternenseemann** [comment]
I think something weird happened when I tried to update the golden files, hang on.

**Comment by sternenseemann** [comment]
Looks /much/ more sensible now!

**Comment by maralorn** [comment]
It’s still unclear to me why there is a new mainProgram appearing if you introduce a filter, but I am sure it is fine.^^

**Comment by sternenseemann** [comment]
> It’s still unclear to me why there is a new mainProgram appearing if you introduce a filter, but I am sure it is fine.^^

If two executables are declared, but only one is buildable, previously no mainProgram would be emitted, but now it would.

E.g. pandoc has `pandoc` and `trypandoc`, but only `pandoc` is buildable by default.

**Comment by maralorn** [comment]
Uh, beautiful! Thx!

**Pull request merged**
