### PR TITLE
Improve nix caching for local packages with subpaths

### PR DESCRIPTION
**Pull request by jmitchell**
Instead of generating this for local packages with subpaths

    src = ./.;
    postUnpack = "sourceRoot+=/dep";

this change generates

    src = ./dep;

The postUnpack strategy is still used for subpaths in remote
repositories.

### CODE REVIEW

**Comment by jmitchell** [comment]
## Remote repo with subpath

```
$ cabal2nix --subpath dep1 https://github.com/jmitchell/haskell-multi-package-demo1.git
...
{ mkDerivation, base, fetchgit, stdenv }:
mkDerivation {
  pname = "dep1";
  version = "0.1.0.0";
  src = fetchgit {
    url = "https://github.com/jmitchell/haskell-multi-package-demo1.git";
    sha256 = "0mxpn41qizy965n9ghjazisvx2ci0mmlq37iyqpji395qf0860s3";
    rev = "e3d9bd6d6066dab5222ce53fb7d234f28eafa2d5";
  };
  postUnpack = "sourceRoot+=/dep1; echo source root reset to $sourceRoot";
  libraryHaskellDepends = [ base ];
  license = stdenv.lib.licenses.bsd3;
}
```

## Local repo with subpath

```
$ cabal2nix --subpath dep1 .   # a local clone of the same repo
{ mkDerivation, base, stdenv }:
mkDerivation {
  pname = "dep1";
  version = "0.1.0.0";
  src = ./dep1;
  libraryHaskellDepends = [ base ];
  license = stdenv.lib.licenses.bsd3;
}
```

**Comment by peti** [comment]
Why would anyone call `cabal2nix --subpath=foo .` instead of `cabal2nix foo` if all files required for the build reside in the sub-directory?

**Comment by jmitchell** [comment]
Using `cabal2nix foo` would mean the resulting nix expression is only useful when the current directory is `foo`, but I use cabal2nix to generate many nix expressions that need to work from the same directory.

```
$ cabal2nix dep1
{ mkDerivation, base, stdenv }:
mkDerivation {
  pname = "dep1";
  version = "0.1.0.0";
  src = ./.;
  libraryHaskellDepends = [ base ];
  license = stdenv.lib.licenses.bsd3;
}
```

**Comment by peti** [comment]
How about `cabal2nix $PWD/foo` then? That works everywhere.

**Comment by jmitchell** [comment]
Ah, I was mixed up. My previous comment was based on the changes in this PR, but in `master` it produces the desired `src = ./dep1`. Thanks, @peti.

**Pull request closed without merging**
