### PR TITLE
Decode .cabal files using UTF-8 instead of system encoding (fixes #333)

### LINKED ISSUE #333: don't depend on LANG=utf-8 being set for interpreting cabal files' encoding properly
Hey!  This probably obvious to everybody with minimal Nix experience, but I lack that basic experience. So here is what I try:

```
$ nix-shell -p cabal2nix --pure --run 'cabal2nix .'
*** parsing cabal file: ././tinc.cabal: hGetContents: invalid argument (invalid byte sequence)
cabal2nix: nix-prefetch-zip: createProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
```

If I run this without `--pure` or install `cabal2nix` into my profile then it works, even though there is no `nix-prefetch-zip` on my `PATH`.  What additional package do I need to pass to `nix-env` to make this work?

### PR DESCRIPTION
**Pull request by sol**

### CODE REVIEW

**Comment by sol** [comment]
There is one more `readFile` in the same module + we might want to look at all places where we read / write files.

**Comment by kmicklas** [comment]
I don't think this fixes #333, even on current cabal2nix master I am unable to run cabal2nix on it's own cabal file (which includes unicode characters).

**Comment by sol** [comment]
> I am unable to run cabal2nix on it's own cabal file

@kmicklas That is interesting.  Running

```
$ LANG=c ./dist/build/cabal2nix/cabal2nix .
```
works for me.  How exactly does it fail for you?  Can you also provide the output of `env` from your box?

**Comment by sol** [comment]
Edit: It work on 38db587a59a401ff88fec7f21fac00d93f7c12c2, current `master` (4f0c2c3b58aacadc204f7b5376ce952a165ae2bf) is broken.

**Comment by peti** [comment]
What is the error messages you guys see, exactly?

**Comment by peti** [comment]
As far as I can tell, everything works just fine:

~~~
❯ g show | cat                                                                    cabal2nix/git/master 
commit 4f0c2c3b58aacadc204f7b5376ce952a165ae2bf
Merge: 63041e4 69873f8
Author: Peter Simons <simons@cryp.to>
Date:   Mon Mar 19 17:16:49 2018 +0100

    Merge pull request #339 from angerman/patch-1
    
    Add `Windows` to platforms.

❯ unset LANG XTERM_LOCALE LC_CTYPE                                                cabal2nix/git/master 
❯ export LANG=de_DE.iso88591                                                      cabal2nix/git/master 
❯ cabal new-run exe:cabal2nix -- cabal://cabal2nix                                cabal2nix/git/master 
Up to date
{ mkDerivation, aeson, ansi-wl-pprint, base, bytestring, Cabal
, containers, deepseq, directory, distribution-nixpkgs, filepath
, hackage-db, hopenssl, hpack, language-nix, lens, monad-par
, monad-par-extras, mtl, optparse-applicative, pretty, process
, split, stdenv, tasty, tasty-golden, text, time, transformers
, yaml
}:
mkDerivation {
  pname = "cabal2nix";
  version = "2.9.1";
  sha256 = "7bc296f42633bc5654fde9c1a11cffb5e54bf6ec5a98597ec4f5baf9b97ce5e3";
  isLibrary = true;
  isExecutable = true;
  libraryHaskellDepends = [
    aeson ansi-wl-pprint base bytestring Cabal containers deepseq
    directory distribution-nixpkgs filepath hackage-db hopenssl hpack
    language-nix lens optparse-applicative pretty process split text
    time transformers yaml
  ];
  executableHaskellDepends = [
    aeson base bytestring Cabal containers directory
    distribution-nixpkgs filepath hopenssl language-nix lens monad-par
    monad-par-extras mtl optparse-applicative pretty
  ];
  testHaskellDepends = [
    base Cabal filepath language-nix lens pretty tasty tasty-golden
  ];
  homepage = "https://github.com/nixos/cabal2nix#readme";
  description = "Convert Cabal files into Nix build instructions";
  license = stdenv.lib.licenses.bsd3;
}
~~~

**Comment by sol** [comment]
```
)$ LANG=c ./dist/build/cabal2nix/cabal2nix .
*** parsing cabal file: user error (cannot parse "././cabal2nix.cabal")
cabal2nix: nix-prefetch-zip: createProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
```

(with 9ef6995, which AFAICT introduced the regression)

**Comment by sol** [comment]
https://github.com/NixOS/cabal2nix/commit/9ef69957950af86e2e6a3eb82adc0514b27bc83b#diff-6046c752b920fc1c56ad7ba056abc284R202

`BS.pack hpackOutput` truncates the `String`.

**Comment by sol** [comment]
As a side note, using `digestString` may also be problematic.

**Comment by peti** [comment]
I don't believe that the error message

    nix-prefetch-zip: createProcess: runInteractiveProcess: exec: does not exist 

is indicative of a language locale problem. Rather, this seems to be an issue with $PATH.

**Comment by peti** [comment]
Interestingly enough, the current `master` version fails completely when the locale environment is set up *correctly*, i.e. when using utf-8 by default:

~~~
cabal new-run exe:cabal2nix -- .
Up to date
*** cannot parse "././cabal2nix.cabal":
cabal2nix.cabal:71:1: "the input" (line 71, column 1):
unexpected character in input '\DLE'
expecting field contents

*** parsing cabal file: user error (*** Exiting.)
unpacking...
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
error: program 'tar' failed with exit code 2
warning: unable to download '.': Couldn't resolve host name (6); retrying in 340 ms
warning: unable to download '.': Couldn't resolve host name (6); retrying in 617 ms
warning: unable to download '.': Couldn't resolve host name (6); retrying in 1038 ms
warning: unable to download '.': Couldn't resolve host name (6); retrying in 2025 ms
error: unable to download '.': Couldn't resolve host name (6)
Initialized empty Git repository in /tmp/git-checkout-tmp-yXGLjFU2/.git/
fatal: Couldn't find remote ref HEAD
fatal: The remote end hung up unexpectedly
fatal: empty string is not a valid pathspec. please use . instead if you meant to match all paths
Unable to checkout HEAD from ..
abort: repository . not found!
svn: E155007: '/home/simons/src/cabal2nix' is not a working copy
failed to open trace file: [Errno 2] No such file or directory: '/homeless-shelter/.bzr.log'
bzr: ERROR: Not a branch: "/home/simons/src/cabal2nix/".
cabal2nix: user error (Failed to fetch source. Does the URL exist?)
~~~

This doesn't look good.

**Comment by sol** [comment]
@peti the error message is not awesome, but that is how encoding errors hit the user.  I was confused about this initially too.  See my comment at https://github.com/NixOS/cabal2nix/issues/333#issuecomment-365898590.

**Comment by sol** [comment]
> nterestingly enough, the current master version fails completely when the locale environment is set up correctly, i.e. when using utf-8 by default:

This is not surprising given that the string is truncated with `BS.pack`.  I'll open a PR shortly.

**Pull request merged**
