### PR TITLE
hackage2nix as a library

### PR DESCRIPTION
**Pull request by bennofs**
This PR splits the parts of hackage2nix which are responsible for generating the package set in a library, fixing #184. I'm sorry if I have duplicated work (I didn't see #184 was assigned until after I already worked on trying to write a stackage2nix). 

I also made the configuring phase (deciding whether to jailbreak, enable tests, etc) a bit more flexible. For example, stackage already contains information on whether to run the tests or not, so it makes sense to be able to directly use of that.

The more flexible package configuration also allowed me to fix a bug in package generation: some packages where needlessly marked as broken, because there tests depend on unavailable packages. The new behavior is that in such a case, the package is not marked as broken, but the tests are disabled. hackage2nix will now try the following configurations, in this order (the first configuration to succeed is used):

* Tests enabled, no jailbreak
* Tests enabled, jailbreak
* Tests disabled, no jailbreak
* Tests disabled, jailbreak

If all of that fails, a broken derivation will be generated. 

The PR also includes some fixes to make hackage2nix use less memory.

### CODE REVIEW

**Comment by peti** [comment]
You might be interested in https://github.com/NixOS/cabal2nix/issues/184#issuecomment-132592633, too.

**Comment by bennofs** [comment]
Regarding memory usage, here are two heap profiles (unfortunately, hp2ps does not seem to have a way to make the colors of both images match).
### Master
master
### With the changes in the PR
new

While the second one looks about constant, the first one is leaking. There are some performance bugs in the cabal flag assignment (the whole first yellow triangle is really cabal trying to finalize a single package with many flags), which show up as spikes in the second graph.

**Comment by bennofs** [comment]
I'll try to see if I can find a way without changing the HackageGit representation.

**Comment by peti** [comment]
What happens when you specify an upper limit on the heap? Does that improve the situation?

**Comment by bennofs** [comment]
@peti I can try that

**Comment by bennofs** [comment]
First, here's what happens when I just remove the IO on my branch. The leak is better visible here:

hackage2nix leak

**Comment by bennofs** [comment]
At least with `-M200M`, it fails with a heap exception, but that might be not enough memory...

**Comment by bennofs** [comment]
It even exhausts the heap with `-M700M`

**Comment by bennofs** [comment]
I give up trying to make this use less memory without changing the hackage db representation. It seems impossible to convince ghc to garbage collect the hackage map while the output is produced.

**Comment by peti** [comment]
I suppose this means that I'll have to consider changing the API of `hackage-db`. Having that lazy map seemed like an obvious choice for parsing that tarball from `cabal-install`, but in retrospect that API isn't so good anymore because it's forces significant costs on users who don't want to have the `GenericPackageDescription`, but who really just want to see the set of available packages.

**Comment by peti** [comment]
I've been thinking about your extended algorithm that potentially disables the test suite in an attempt to salvage the build. Is that behavior desirable? I mean, I want the test suite for my packages to run, and if that's not possible for whatever reason, then I want the build to *fail*. This is essential for my use of Hydra/Nix as a Continuous Integration tool. Now, if `hackage2nix` would decide to disable the test suite on one of my packages in an attempt to make a build succeed that would otherwise fail, then I'd be rather annoyed, actually.

How do you feel about that issue?

**Comment by bennofs** [comment]
I agree with you on this. The issue again is that the package itself and the test run of it aren't separate: as an end-user, I might want to choose not to run the tests, but still use the binary cache for the library itself.

Note however that tests are *only* disabled when the test suite depends on library that is not available in nixpkgs. IMO, that means that the tests are broken, not the package as a whole. But that's currently not expressible in nixpkgs, so I'm fine with either way.

**Comment by peti** [comment]
I suppose this PR has become obsolete.

**Pull request closed without merging**
