### PR TITLE
chore: convert xscrnsaver to xlibs.libXScrnSaver

### PR DESCRIPTION
**Pull request by teto**

### CODE REVIEW

**Comment by teto** [comment]
following up on https://github.com/NixOS/nixpkgs/pull/124593

**Review by peti — CHANGES_REQUESTED** [review]
The "xlibs." prefix should be unnecessary.

**Comment by teto** [comment]
done. I couldn't find an easy way to test (this repo weirdly doesnt provide a shell.nix/flake.nix to check one's changes, the regenerate scripts fail because they ask for a nixpkgs). Hope that's good.

**Comment by sternenseemann** [comment]
Shouldn't it be `xorg.libXScrnSaver`? top level `libXScrnSaver` is not a thing.

**Comment by teto** [comment]
which is why I had used xlibs.libXScrnSaver (`nix-build -A xlibs.libXScrnSaver` works fine here).  I've checked the box for maintainers to edit since you know better how cabal2nix does the mapping.

**Comment by sternenseemann** [comment]
`xlibs` is a deprecated alias for `xorg`, so we should use the latter definitely.

**Comment by teto** [comment]
I've just noticed that in the line below my change Xss references libXScrnSaver directly so maybe that 's why @peti made his comment ? looking at hackage-packages.nix  it seems cabal2nix is smart enough to do `inherit (pkgs.xorg) libXScrnSaver; ` so I think @peti may be right.

**Comment by sternenseemann** [comment]
Yeah distribution-nixpkgs does that, I should know that.

**Comment by cdepillabout** [comment]
@teto Thanks for taking the time to put this together.

I tried regenerating `hackage-packages.nix` with this change and it appears to working:

```diff
diff --git a/pkgs/development/haskell-modules/hackage-packages.nix b/pkgs/development/haskell-modules/hackage-packages.nix
index ec260563848..ccdef5fd12b 100644
--- a/pkgs/development/haskell-modules/hackage-packages.nix
+++ b/pkgs/development/haskell-modules/hackage-packages.nix
@@ -110881,9 +110881,9 @@ self: {
 
   "greenclip" = callPackage
     ({ mkDerivation, base, binary, bytestring, directory, exceptions
-     , hashable, libXau, microlens, microlens-mtl, protolude, text
-     , tomland, unix, vector, wordexp, X11, xcb, xdmcp, xlibsWrapper
-     , xscrnsaver
+     , hashable, libXau, libXScrnSaver, microlens, microlens-mtl
+     , protolude, text, tomland, unix, vector, wordexp, X11, xcb, xdmcp
+     , xlibsWrapper
      }:
      mkDerivation {
        pname = "greenclip";
@@ -110896,14 +110896,14 @@ self: {
          microlens-mtl protolude text tomland unix vector wordexp X11
        ];
        executablePkgconfigDepends = [
-         libXau xcb xdmcp xlibsWrapper xscrnsaver
+         libXau libXScrnSaver xcb xdmcp xlibsWrapper
        ];
        description = "Simple clipboard manager to be integrated with rofi";
        license = lib.licenses.bsd3;
        hydraPlatforms = lib.platforms.none;
        broken = true;
-     }) {inherit (pkgs.xorg) libXau; xcb = null; xdmcp = null; 
-         inherit (pkgs) xlibsWrapper; xscrnsaver = null;};
+     }) {inherit (pkgs.xorg) libXScrnSaver; inherit (pkgs.xorg) libXau; 
+         xcb = null; xdmcp = null; inherit (pkgs) xlibsWrapper;};
 
   "greg-client" = callPackage
     ({ mkDerivation, base, binary, bytestring, clock, hostname, network
```

**Pull request merged**
