### PR TITLE
hackage2nix: ignore aliases

### PR DESCRIPTION
**Pull request by jtojnar**
Real solution to https://github.com/NixOS/cabal2nix/pull/410

Depends on https://github.com/peti/distribution-nixpkgs/pull/6

### CODE REVIEW

**Comment by jtojnar** [comment]
When I ran `hackage2nix` locally, it fixed the majority of issues. Paging through diff, some new appeared:

* `gnome-keyring` had `libgnome_keyring` changed to `null`
* `webkit2gtk3-javascriptcore` had `webkitgtk` changed to `null` (though some other packages like `webkit-javascriptcore` did not)
* `qr-imager` had `libqrencode` changed to `null`

**Comment by jtojnar** [comment]
Nah, it looks like `pkgs.gnome2.gtk` is still used.

**Comment by peti** [comment]
> When I ran `hackage2nix` locally, it fixed the majority of issues. Paging through diff, some new appeared: [...]

These name lookups are fixed by 50125218b2a2bdafe6bbebf28626b85e73900d51.

**Comment by peti** [comment]
Thank you very much for your help!

**Pull request closed without merging**
