### PR TITLE
resolveInNixpkgs: stop using GNOME aliases

### PR DESCRIPTION
**Pull request by jtojnar**
They were removed in https://github.com/NixOS/nixpkgs/pull/55735

### CODE REVIEW

**Comment by jtojnar** [comment]
Maybe we can get rid of those lines and just rely on the line 143.

**Comment by ryantm** [comment]
There's also gobject-introspection.

**Comment by ryantm** [comment]
Oh, maybe that is going to get handled correctly by using the latest nixpkgs.

**Comment by jtojnar** [comment]
We probably need to run `nix-env -qaP` with `--arg config '{ allowAliases = false; }` to prevent the aliases from being used and tripping OfBorg.

**Pull request merged**
