### PR TITLE
Add hack for common erroneous missing build-tool-depends, and keep duplicate deps for cross

### LINKED ISSUE #356: Maintain hardcoded build tool dependency mapper
See https://github.com/commercialhaskell/stack/pull/4132/files#diff-9fe1770b08b2871a8d3e3e229168b13dR725

### PR DESCRIPTION
**Pull request by Ericson2314**
See comment in code for more details.

The cross change is unambiguously a good thing, and put in the first commit. The `*-discover` hack is more a stop-gap until packages stop being broken---we're *not* hacking around a Nix deficiency with `strictDeps` here. It relies on the cross change because rather than changing what sort of dependency `*-discover` is, it adds a new dependency in case it was actually wanted as a library, which would be removed.

Fixes #356

CC @matthewbauer @domenkozar

### CODE REVIEW

**Comment by domenkozar** [comment]
Also needs: hsx2hs, markdown-unlit.

**Comment by Ericson2314** [comment]
@domenkozar OK will do.

Any idea what's going on with CI? Seems like a preexisting issue.

**Comment by domenkozar** [comment]
@Ericson2314 you're hitting https://github.com/NixOS/cabal2nix/issues/359

**Comment by Ericson2314** [comment]
Thanks!

**Comment by Ericson2314** [comment]
@peti? You seen this yet?

**Comment by peti** [comment]
The CI problems are fix now.

**Comment by Ericson2314** [comment]
Thanks! rebased and pushed.

**Comment by domenkozar** [comment]
```
src/Distribution/Nixpkgs/Haskell/FromCabal/PostProcess.hs:24:12: Warning: Redundant bracket
Found:
  (id)
Perhaps:
  id
src/Distribution/Nixpkgs/Haskell/FromCabal/PostProcess.hs:60:37: Warning: Redundant bracket
Found:
  (id)
Perhaps:
  id
2 hints
```

**Comment by Ericson2314** [comment]
@domenkozar thanks for fishing that out. Ran `hlint` locally too.

**Comment by Ericson2314** [comment]
OK cool it built. I guess next step is to revive up strictdeps patch with this while waiting for review? I see how to regenerate nixpkgs, but not sure what the normal flow (e.g. push to hackage then use that version?) so I'll let @peti do that.

**Comment by domenkozar** [comment]
Now we need to include strictDeps change and reenable all packages since many should build now (mostly macos). @Ericson2314 are you going to re-do that PR?

**Comment by domenkozar** [comment]
This still doesn't add hspec-discover for packages that don't declare it as dependency such as unliftio:

```
  "unliftio" = callPackage
    ({ mkDerivation, async, base, deepseq, directory, filepath, hspec
     , process, stm, time, transformers, unix, unliftio-core
     }:
     mkDerivation {
       pname = "unliftio";
       version = "0.2.7.0";
       sha256 = "0qql93lq5w7qghl454cc3s1i8v1jb4h08n82fqkw0kli4g3g9njs";
       libraryHaskellDepends = [
         async base deepseq directory filepath process stm time transformers
         unix unliftio-core
       ];
       testHaskellDepends = [
         async base deepseq directory filepath hspec process stm time
         transformers unix unliftio-core
       ];
       description = "The MonadUnliftIO typeclass for unlifting monads to IO (batteries included)";
       license = stdenv.lib.licenses.mit;
     }) {};
```

**Comment by Ericson2314** [comment]
I think that's reasonable.

**Pull request merged**
