### PR TITLE
libudev -> systemd

### PR DESCRIPTION
**Pull request by volth**
one more alias left in https://github.com/NixOS/nixpkgs/pull/43872

### CODE REVIEW

**Comment by volth** [comment]
https://github.com/NixOS/nixpkgs/pull/43872#issuecomment-406860466

**Comment by peti** [comment]
Thank you.

**Comment by volth** [comment]
Please re-run it, as https://github.com/NixOS/nixpkgs/commit/0ac253da1c4f72ceaf08a0734e2d4f0605bd81c6 restored ```libudev``` (which is forbidden since https://github.com/NixOS/nixpkgs/commit/0d8076b99cce5c6638abeb28153c42f698e1bc18) and broke the master

**Comment by peti** [comment]
I pushed 4ea202d328d697c4453784c1faedf165b1591c3c to fix the issue. The next proper update is going to take a day or two because we just bumped to LTS 12.2.

**Pull request merged**
